# Generated by Django 3.1.4 on 2021-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('item', models.FileField(upload_to='')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
