# Generated by Django 3.1.4 on 2021-02-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
